basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('register/', include('register.urls', namespace='register')),
    path('login/', include('register.urls'), name='login'),
    path('logout/', include('register.urls'), name='logout'),
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/urls.py
from django.urls import path

from . import views

app_name = 'register'

urlpatterns = [
    path('', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout')
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('product_crud', views.product_crud, name='product_curd'),
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),

    path(r'update_product/(?P<id>.+)', views.product_crud, name='update_product'),
    path(r'delete_product/(?P<id>.+)', views.delete_product, name='delete_product'),

]

register/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

# Create your models here.

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

store/forms.py
from .models import Product
from django import forms


class ProductFrom(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'category', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

register/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from .models import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


# Create your views here.


def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            userContext = {'user': user}
            messages.success(request, 'Account was created successfully')
            return redirect('/login/login/')
    context = {'form': form}
    return render(request, 'store/products/register.html', context)


def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                userContext = {'user': user}
                return redirect('/', userContext)
        else:
            messages.info(request, 'User Name or Password incorrect')
            return render(request, 'store/products/login.html')
    return render(request, 'store/products/login.html')

def logoutUser(request):
    if request.user.is_anonymous:
        return redirect('/')
    logout(request)
    return redirect('/')

store/views.py
from django.shortcuts import get_object_or_404, render, redirect

from .models import Category, Product
from .forms import ProductFrom


def product_crud(request, id=0):
    if request.user.is_authenticated and request.user.is_superuser:
        if id == 0:
            form = ProductFrom(request.POST or None)
        else:
            if request.method == 'GET':
                form = ProductFrom(instance=Product.objects.get(id=id))
            else:
                form = ProductFrom(request.POST, instance=Product.objects.get(id=id))
            products = Product.objects.all()
            context = {'products': products, 'form': form}
        if form.is_valid():
            form.save()
            form = ProductFrom()
        products = Product.objects.all()
        messages = form.errors
        context = {'products': products, 'form': form, 'messages': messages}
        return render(request, 'store/product_crud.html', context)
    else:
        return redirect('/login/login')


def product_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    if product is None:
        return redirect('/')
    return render(request, 'store/products/single.html', {'product': product})


def delete_product(request, id):
    Product.objects.get(id=id).delete()
    return redirect('/product_crud')

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="container">
    <div class="row">
      <div class="album py-5">


        <div class="pb-3"><h1 class="h3">Popular</h1></div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

          {% for product in products %}

          <div class="col">
            <div class="card border-0">
              <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
              <div class="card-body px-0">
                <p class="card-text">
                  <a class="text-dark text-decoration-none"
                    href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">£{{product.price}}</small>
                </div>
              </div>
            </div>
          </div>

          {% endfor %}

        </div>
      </div>
    </div>

  </div>


</main>

{% endblock %}

templates/store/products/detail.html
{% extends "store/base.html" %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end"><button type="button" class="btn btn-secondary btn-sm">Add to
                                    basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>
{% endblock %}

templates/store/products/login.html
{% extends "../base2.html" %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
    <style>

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #000000;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title{
            color: #fff;

        }

        .login_btn {
            width: 100%;
            background: #003366 !important;
            color: white !important;
        }
        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }
        .login_container {
            padding: 0 2rem;
        }
        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }
        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages{
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100 mt-5">
            <div class="user_card">
                <div class="d-flex justify-content-center">


                    <h3 id="form-title">LOGIN</h3>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name="username" placeholder="Username..." class="form-control">
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" name="password" placeholder="Password..." class="form-control" >
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Login">
                        </div>
                    </form>
                </div>
                <div class="mt-4">
                    {% for message in messages %}
                        <p id="messages">{{ message }}</p>
                    {% endfor %}
                    <div class="d-flex justify-content-center links">
                       Don't have an account? <a href="/register/" class="ml-2">Sign Up</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/store/products/register.html
{% extends "../base2.html" %}
{% load static %}
{% block title %}Register{% endblock %}
{% block content %}
    <style>
        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #000000;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title{
            color: #fff;
        }
        .login_btn {
            width: 100%;
            background: #003366 !important;
            color: white !important;
        }
        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }
        .login_container {
            padding: 0 2rem;
        }
        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }
        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

    </style>
    <body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100 mt-5">
            <div class="user_card">
                <div class="d-flex justify-content-center">
                    <h3 id="form-title">REGISTER ACCOUNT</h3>
                </div>
                <div class="d-flex justify-content-center form_container">

                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            {{form.username}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                            </div>
                            {{form.email}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password1}}
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            {{form.password2}}
                        </div>

                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Register Account">
                        </div>
                    </form>
                </div>
                {% for message in form.erros %}
                    <p id="messages">message</p>
                {% endfor %}
                {{ form.errors }}
                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Already have an account? <a href="/login/login/" class="ml-2">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field
*/

        //Query All input fields
        var form_fields = document.getElementsByTagName('input')
        form_fields[0].placeholder='Username..';
        form_fields[1].placeholder='Email..';
        form_fields[2].placeholder='Enter password...';
        form_fields[3].placeholder='Re-enter Password...';


        for (var field in form_fields){
            form_fields[field].className += ' form-control'
        }
    </script>
    </body>
{% endblock %}

templates/store/products/single.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}


<main class="pt-2">

  <div class="container" style="max-width: 1000px">

    <div class="row g-3">
          <div class="alert alert-primary fw600 rounded-0 border-0 py-3" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-info-circle me-2"
        viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
        <path
          d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
      </svg>
      COVID-19 - <u>Click here for our latest updates</u> on our stores, website and contact centre. Thank you for
      your patience and support.
    </div>
        <div class="col-12 d-flex justify-content-between">

        </div>

        <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
            <div class="d-grid gap-2">

            <div class="d-flex d-flex-inline justify-content-between">
            <div><span class="h3">£{{ product.price }}</span><p class="text-muted">includes tax</p></div>
                   <div class="">
                                <label for="select">Qty</label>
                                <select id="select" class="h6" style="width:50px;height:40px;">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>
                    </div>
            </div>
            <hr>
            <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to basket</button>
            <button type="button" id="add-button" value="{{product.id}}" class="btn btn-light fw500">Add to Favorites</button>
            </div>
        </div>

        <div class="col-md-7 col-lg-7 p-0">



            <div class="card mb-3 border-0">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-body p-1">
                        <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
                        <div class="bg-light"><img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}"> </div>
                    </div>

                </div>
            </div>
            </div>



        </div>

    </div>
  </div>
</main>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}